### ISSUE TITLE
/oldest — показать самые старые заметки

### ISSUE THREAD

**Issue by kemphack** [MCL1303/TaskBot#28]
Добавить команду боту для выведения динамического списка.

**Comment by cblp** [comment]
ты имеешь в виду команды вообще или только стандартные — /start, /help?

**Comment by kemphack** [comment]
Да.

**Comment by cblp** [comment]
лучше завести отдельную задачу на каждую команду

**Comment by kemphack** [comment]
Хорошо, значит эта будет для показа, только как получше назвать? /todolist ?

**Comment by cblp** [comment]
а что ты хочешь показать? все-все-все заметки? их может быть очень-очень-очень много

**Comment by cblp** [comment]
в интерфейсе телеграмма лучше больше 3 сообщений сразу не присылать.

мне было бы интересно увидеть 3 случайных заметки, потом ещё 3 случайных и т. д.

или 3 самых старых, потом 3 менее старых и т. д.

или 3 самых новых, потом 3 менее новых и т. д.

вот уже 3 команды получилось

**Comment by kemphack** [comment]
Можно будет сделать пролистываемый список, у которого будут кнопочки, чтобы можно передвигаться по списку.

**Comment by cblp** [comment]
1. это сложно
2. я не могу себе это представить в деталях. ты такое в Телеграме видел?

**Comment by cblp** [comment]
давай начнём с выборки 3 самых старых? тем более, такая функциональность уже есть. команду назовём `/oldest`.
