### ISSUE TITLE
Автоматически обновлять список команд

### ISSUE THREAD

**Issue by cblp** [MCL1303/TaskBot#43]
через API BotFather

**Comment by kemphack** [comment]
Я знаю только один способ обновлять команды... Это хранить их список с описанием, потом отправлять его BotFather'у.

**Comment by cblp** [comment]
Да, именно это я имел в виду. Только ещё проверять, что список корректен.

**Comment by cblp** [comment]
Кажется, такой фичи нет, только вручную.
