### ISSUE TITLE
UTF-8 symbols in HTTPS request

### ISSUE THREAD

**Issue by kemphack** [MCL1303/TaskBot#5]
При попытке бота сделать get запрос с киррилицей выходит еррор. Как я понимаю, чтобы это поправить, нужно реализовать URL encoding. Только откуда его брать не знаю.

**Comment by cblp** [comment]
опиши, в чём проблема

**Comment by kemphack** [comment]
При попытке бота сделать get запрос с киррилицей выходит еррор. Как я понимаю, что это поправить, нужно реализовать URL encoding. Только откуда его брать не знаю.

**Comment by cblp** [comment]
В разных частях урла применяются разные способы кодирования. Лучше не заниматься этим самостоятельно, а использовать существующие инструменты так, чтобы они сами всё за тебя сделали.

Надо сначала разобрать запрос без параметров функцией parseRequest, потом добавить к запросу соответствующий параметр. Всё кодирование http-client сделает сам.

**Comment by cblp** [comment]
Надо только закодировать в UTF8 ByteString, а дальше http-client сам сработает.

```haskell
λ> r0 <- parseRequest "https://example.com"
λ> let r1 = setQueryString [("text", Just $ encodeUtf8 "привет")] r0
λ> getUri r1
https://example.com:443/?text=%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82
```

**Comment by cblp** [comment]
закодировать в UTF8 с помощью функции [text:Data.Text.Encoding.encodeUtf8](http://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text-Encoding.html#v:encodeUtf8)
