### ISSUE TITLE
Внедрить telegram-api

### ISSUE THREAD

**Issue by cblp** [MCL1303/TaskBot#7]

**Comment by kemphack** [comment]
А какие именно мы хотим внедрить функции из телеграма?

**Comment by cblp** [comment]
Не из тегеграма, а из пакета *telegram-api*. Для начала вот эти — *[getUpdatesM](https://hackage.haskell.org/package/telegram-api/docs/Web-Telegram-API-Bot-API-Updates.html#v:getUpdatesM)* и *[sendMessageM](https://hackage.haskell.org/package/telegram-api/docs/Web-Telegram-API-Bot-API-Messages.html#v:sendMessageM)*.

**Comment by kemphack** [comment]
А нельзя оставить наши функции?

**Comment by cblp** [comment]
Если оставить их сейчас, то потом придётся тратить время на дописывание ещё и ещё велосипедов, тратить время на исправление ошибок в них и т. д. Вместо этого можно просто взять готовые функции, делающие чёрную работу, а самому писать только смаое интересное.
